---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: account-app
  template:
    metadata:
      labels:
        name: account-app
    spec:
      containers:
      - image: techsophyofficial/awgment-app-account:$IMAGE_VERSION
#      - image: tsdevopsteam/platform:account-app-$BUILD_NUMBER
        name: account-app
        envFrom:
        - configMapRef:
            name: $CONFIG_MAP
#            name: accountapp-env
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ts-platform



---
apiVersion: v1
kind: Service
metadata:
  name: account-app
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: account-app