---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: account-app
  template:
    metadata:
      labels:
        name: account-app
    spec:
      containers:
      - image: techsophyofficial/awgment-app-account:$IMAGE_VERSION
        name: account-app
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: $CONFIG_MAP

        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: account-app