---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: account-app
  template:
    metadata:
      labels:
        name: account-app
    spec:
      containers:
      - image: tsdevopsteam/platform:account-app-$BUILD_NUMBER
        name: account-app
        envFrom:
        - configMapRef:
            name: accountapp-env      
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: certificate-pem
          mountPath: /etc/ssl/certs/public_key_rsa_4096_pkcs8-exported.pem
          subPath: public_key_rsa_4096_pkcs8-exported.pem
      volumes:
       - name: certificate-pem
         configMap:
           name: certificate-pem
      imagePullSecrets:
      - name: ts-platform



---
apiVersion: v1
kind: Service
metadata:
  name: account-app
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: account-app
